_target_: src.datamodules.focus_datamodule.FocusDataModule

data_dir: ${data_dir}/focus # data_dir is specified in config.yaml
csv_file: ${data_dir}/focus/metadata.csv
batch_size: 64
train_val_test_split_percentage: [0.7, 0.15, 0.15]
num_workers: 0
pin_memory: False
