version: "3"  # optional since v1.27.0
services:
  preprocess:
    build: .
    volumes:
      - ./out/:/usr/src/app/out:z
      - ./in/:/usr/src/app/in:z
    env_file:
      - .env
    network_mode: host # use host networking; you can also just link container networks directly
